# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi/okta-management/management.yaml:
  tag-description:
    - '#/tags/0/description'
    - '#/tags/1/description'
    - '#/tags/2/description'
    - '#/tags/3/description'
    - '#/tags/5/description'
    - '#/tags/6/description'
    - '#/tags/7/description'
    - '#/tags/8/description'
    - '#/tags/9/description'
    - '#/tags/10/description'
    - '#/tags/11/description'
    - '#/tags/12/description'
    - '#/tags/13/description'
    - '#/tags/14/description'
    - '#/tags/15/description'
    - '#/tags/16/description'
    - '#/tags/17/description'
    - '#/tags/18/description'
    - '#/tags/19/description'
    - '#/tags/20/description'
    - '#/tags/21/description'
    - '#/tags/22/description'
    - '#/tags/23/description'
    - '#/tags/24/description'
    - '#/tags/25/description'
  no-ambiguous-paths:
    - '#/paths/~1api~1v1~1groups~1{groupId}~1apps'
    - '#/paths/~1api~1v1~1groups~1{groupId}~1roles'
    - '#/paths/~1api~1v1~1groups~1{groupId}~1users'
  no-invalid-media-type-examples:
    - '#/components/examples/ListEmailCustomizationResponse/value/0/language'
    - '#/components/examples/ListEmailCustomizationResponse/value/0/isDefault'
    - '#/components/examples/ListEmailCustomizationResponse/value/0/id'
    - '#/components/examples/ListEmailCustomizationResponse/value/0/created'
    - '#/components/examples/ListEmailCustomizationResponse/value/0/lastUpdated'
    - '#/components/examples/ListEmailCustomizationResponse/value/0/_links'
    - '#/components/examples/ListEmailCustomizationResponse/value/0/subject'
    - '#/components/examples/ListEmailCustomizationResponse/value/0/body'
    - '#/components/examples/CreateUpdateEmailCustomizationRequest/value/language'
    - >-
      #/components/examples/CreateUpdateEmailCustomizationRequest/value/isDefault
    - '#/components/examples/CreateUpdateEmailCustomizationRequest/value/subject'
    - '#/components/examples/CreateUpdateEmailCustomizationRequest/value/body'
    - >-
      #/components/examples/CreateUpdateEmailCustomizationResponse/value/language
    - >-
      #/components/examples/CreateUpdateEmailCustomizationResponse/value/isDefault
    - '#/components/examples/CreateUpdateEmailCustomizationResponse/value/id'
    - '#/components/examples/CreateUpdateEmailCustomizationResponse/value/created'
    - >-
      #/components/examples/CreateUpdateEmailCustomizationResponse/value/lastUpdated
    - '#/components/examples/CreateUpdateEmailCustomizationResponse/value/_links'
    - '#/components/examples/CreateUpdateEmailCustomizationResponse/value/subject'
    - '#/components/examples/CreateUpdateEmailCustomizationResponse/value/body'
    - '#/components/examples/EmailCustomizationResponse/value/language'
    - '#/components/examples/EmailCustomizationResponse/value/isDefault'
    - '#/components/examples/EmailCustomizationResponse/value/id'
    - '#/components/examples/EmailCustomizationResponse/value/created'
    - '#/components/examples/EmailCustomizationResponse/value/lastUpdated'
    - '#/components/examples/EmailCustomizationResponse/value/_links'
    - '#/components/examples/EmailCustomizationResponse/value/subject'
    - '#/components/examples/EmailCustomizationResponse/value/body'
    - '#/components/examples/EmailTemplateDefaultContentResponse/value/_links'
    - '#/components/examples/EmailTemplateDefaultContentResponse/value/subject'
    - '#/components/examples/EmailTemplateDefaultContentResponse/value/body'
    - >-
      #/components/examples/PreviewEmailTemplateDefaultContentResponse/value/_links/defaultContent
  no-unused-components:
    - '#/components/schemas/UserIdString'
