# This file is here entirely for a developer's machine.
#
# It is what causes:
#
# 1) the `yarn install` command within okta-oas3 to use yarn classic instead of yarn 3
#
# This is necessary so that the lock file updates are in the proper
# yarn 1 format that will work with redocly's CI
yarnPath: ./.yarn/releases/yarn-1.22.19.cjs
